[package]
name = "pp"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Shared core for pp: repository index & search"

[dependencies]
directories.workspace = true
rayon.workspace = true
fst.workspace = true
serde.workspace = true
toml.workspace = true

[lints]
workspace = true
